services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: backend
      SERVER_TYPE: internal_backend
      HEALTH_FAIL_RATE: 0
    networks:
      - my-network

  loadbalancer:
    build:
      context: .
      dockerfile: loadbalancer/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge